// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:c905de10-f39f-47cd-a9c2-8370972c4955',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'mysite-hosting-mobilehub-1075685158',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1c3fs0fokfcrm.cloudfront.net',
    'aws_mobile_analytics_app_id': '9adf862b75cd43129e96a7bc27cfd5ba',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'cd97d3ca-6818-4016-ab6f-7feab6f9d0c8',
    'aws_project_name': 'my-site-2019-05-23-15-26-25',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'mysite-mobilehub-1075685158',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_DjCOKBTyW',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '4mci5fh3h725vlsjp0jk5da5hv',
}

export default awsmobile;
