const AWS_ACCESS_KEY = 'AKIAWDALU4BZLFAMX7WG';
const AWS_SECRET_KEY = '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';
const AWS_REGION = 'us-east-1';

module.exports = {
    AWS_ACCESS_KEY,
    AWS_SECRET_KEY,
    AWS_REGION
};
